# ================= MOTIVASI SYSTEM =================
import random

QUOTES = [

"🌿 Jᴀɴɢᴀɴ ʜɪᴛᴜɴɢ ʜᴀʀɪ. Jᴀᴅɪᴋᴀɴ ʜᴀʀɪ-ʜᴀʀɪ ɪɴɪ ʙᴇʀᴀʀᴛɪ.",
"✨ Jᴀᴅɪʟᴀʜ ᴠᴇʀsɪ ᴛᴇʀʙᴀɪᴋ ᴅᴀʀɪ ᴅɪʀɪᴍᴜ sᴇɴᴅɪʀɪ.",
"🔥 Sᴀᴛᴜ-sᴀᴛᴜɴʏᴀ ᴋᴇsᴀʟᴀʜᴀɴ ᴀᴅᴀʟᴀʜ ᴛɪᴅᴀᴋ ʙᴇʟᴀᴊᴀʀ ᴅᴀʀɪɴʏᴀ.",
"📖 Kᴀᴍᴜ ᴀᴅᴀʟᴀʜ ᴘᴇɴᴜʟɪs ʜɪᴅᴜᴘᴍᴜ sᴇɴᴅɪʀɪ.",
"💭 Rᴀɢᴜ ʜᴀɴʏᴀ ᴍᴇɴᴜɴᴅᴀ ᴋᴇsᴜᴋsᴇsᴀɴ.",
"⚡ Jᴀɴɢᴀɴ ᴛᴜɴɢɢᴜ ᴍᴏᴛɪᴠᴀsɪ, ʙᴜᴀᴛ ᴍᴏᴛɪᴠᴀsɪ ᴍᴜ sᴇɴᴅɪʀɪ.",
"🚀 Hᴀʀɪ ɪɴɪ ᴀᴅᴀʟᴀʜ ʟᴀɴɢᴋᴀʜ ᴋᴇ ᴍᴀsᴀ ᴅᴇᴘᴀɴ.",
"🧠 Yᴀɴɢ ᴍᴇᴍʙᴇᴅᴀᴋᴀɴ ᴀᴅᴀʟᴀʜ ᴛɪɴᴅᴀᴋᴀɴ, ʙᴜᴋᴀɴ ɴɪᴀᴛ.",
"💪 Lᴇʟᴀʜ ɪᴛᴜ ᴡᴀᴊᴀʀ, ɴʏᴇʀᴀʜ ɪᴛᴜ ᴘɪʟɪʜᴀɴ.",
"🕊 Kᴇᴛᴇɴᴀɴɢᴀɴ ᴅᴀᴛᴀɴɢ ᴋᴇᴛɪᴋᴀ ᴋᴀᴍᴜ ʙᴇʀʜᴇɴᴛɪ ᴍᴇɴᴅᴇɴɢᴀʀᴋᴀɴ ᴅᴜɴɪᴀ.",
"🌍 Mᴀɴᴜsɪᴀ ᴅɪ ᴄɪᴘᴛᴀᴋᴀɴ ᴅᴀʀɪ ᴛᴀɴᴀʜ, ʙᴜᴋᴀɴ ᴜɴᴛᴜᴋ ʙᴇʀsɪᴋᴀᴘ ʟᴇᴍᴀʜ.",
"❤️ Hᴀʀɢᴀɪ ᴘʀᴏsᴇs, ʙᴜᴋᴀɴ ʜᴀsɪʟ sᴀᴊᴀ.",
"🌟 Sᴇᴍᴜᴀ ᴏʀᴀɴɢ ᴘᴇʀɴᴀʜ ɢᴀɢᴀʟ, ᴛᴀᴘɪ ᴛɪᴅᴀᴋ sᴇᴍᴜᴀ ʙᴇʀʜᴇɴᴛɪ.",
"🔥 Jᴀᴅɪʟᴀʜ ʟᴇʙɪʜ ᴅᴀʀɪ ᴋᴇᴍᴀʀɪɴ.",
"🌈 Sᴇᴛɪᴀᴘ ʜᴀʀɪ ᴀᴅᴀʟᴀʜ ᴘᴇʟᴜᴀɴɢ ʙᴀʀᴜ.",
"💥 Kᴇʀᴊᴀ ᴋᴇʀᴀs ᴛɪᴅᴀᴋ ᴘᴇʀɴᴀʜ ᴍᴇmbᴏʜᴏɴɢɪ ʜᴀsɪʟ.",
"🌙 Bᴇʟᴀᴊᴀʀ ᴅᴀʀɪ ᴋᴇɢᴀɢᴀʟᴀɴ.",
"🧭 Jᴀɴɢᴀɴ ʜɪʟᴀɴɢ ᴀʀᴀʜ, ʜɪʟᴀɴɢᴋᴀɴ ᴋᴇʀᴀɢᴜᴀɴ.",
"⚔️ Hɪᴅᴜᴘ ᴀᴅᴀʟᴀʜ ᴘᴇʀᴊᴜᴀɴɢᴀɴ.",
"🏆 Sᴜᴋsᴇs ᴅɪᴍᴜʟᴀɪ ᴅᴀʀɪ ᴋᴇʙɪᴀsᴀᴀɴ ᴋᴇᴄɪʟ.",

# ================= TAMBAHAN =================
"🌿 Tᴇɴᴀɴɢ ʙᴜᴋᴀɴ ʙᴇʀᴀʀᴛɪ ʟᴇᴍᴀʜ.",
"⚡ Sᴇᴘᴇʀᴛɪ ʟɪsᴛʀɪᴋ, ᴋᴇᴄɪʟ ᴛᴀᴘɪ ʙᴇʀᴅᴀᴍᴘᴀᴋ.",
"🚀 Sᴀᴀᴛ ᴏʀᴀɴɢ ʟᴀɪɴ ʙᴇʀʜᴇɴᴛɪ, ᴋᴀᴍᴜ ᴍᴀsɪʜ ᴊᴀʟᴀɴ.",
"🧠 Pɪᴋɪʀᴀɴ ᴍᴇɴᴇɴᴛᴜᴋᴀɴ ᴀʀᴀʜ ʜɪᴅᴜᴘ.",
"💪 Kᴇᴋᴜᴀᴛᴀɴ ᴅᴀᴛᴀɴɢ ᴅᴀʀɪ ᴘᴇʀᴊᴜᴀɴɢᴀɴ.",
"🕊 Kᴀᴍᴜ ʙɪsᴀ ʟᴇʙɪʜ ᴅᴀʀɪ ʏᴀɴɢ ᴋᴀᴍᴜ ᴘɪᴋɪʀᴋᴀɴ.",
"🌍 Dᴜɴɪᴀ ᴛɪᴅᴀᴋ ᴍᴇɴᴜɴɢɢᴜ.",
"🔥 Jᴀɴɢᴀɴ ᴛᴜɴᴅᴀ, ᴡᴀᴋᴛᴜ ᴛɪᴅᴀᴋ ᴋᴇᴍʙᴀʟɪ.",
"🌟 Bᴇʀɪ ᴍᴀᴋɴᴀ ᴘᴀᴅᴀ ʟᴀɴɢᴋᴀʜ.",
"💥 Kᴀᴍᴜ ᴀᴅᴀʟᴀʜ ᴇɴᴇʀɢɪ ᴛᴀɴᴘᴀ ʙᴀᴛᴀs.",
"🌈 Sᴇᴛɪᴀᴘ ʟᴜᴋᴀ ᴍᴇᴍʙᴇɴᴛᴜᴋ ᴋᴇᴋᴜᴀᴛᴀɴ.",
"🚀 Jᴀᴅɪʟᴀʜ ɪɴsᴘɪʀᴀsɪ ʙᴜᴋᴀɴ ᴘᴇɴɪʀᴜ.",
"🧠 Pɪʟɪʜᴀɴ ᴍᴇɴᴇɴᴛᴜᴋᴀɴ ᴍᴀsᴀ ᴅᴇᴘᴀɴ.",
"💪 Sᴇʟᴀʟᴜ ᴀᴅᴀ ᴀʟᴀsᴀɴ ᴜɴᴛᴜᴋ ʙᴇʀᴛᴀʜᴀɴ.",
"🕊 Kᴇᴅᴀᴍᴀɪᴀɴ ᴅɪᴍᴜʟᴀɪ ᴅᴀʀɪ ᴅɪʀɪ.",
"🌍 Tɪᴅᴀᴋ ᴀᴅᴀ ʙᴀᴛᴀs ᴜɴᴛᴜᴋ ʙᴇʀᴜsᴀʜᴀ.",
"🔥 Sᴇᴍᴀɴɢᴀᴛ ᴛɪᴅᴀᴋ ᴍᴀᴛɪ.",
"🌟 Kᴀᴍᴜ ʙɪsᴀ ᴊɪᴋᴀ ᴋᴀᴍᴜ ᴍᴀᴜ.",
"💥 Jᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ᴛᴇɴɢᴀʜ ᴊᴀʟᴀɴ.",
"🌈 Hɪᴅᴜᴘ ɪᴛᴜ ᴘᴇʟᴀᴊᴀʀᴀɴ.",
"🚀 Sᴇᴍᴀᴋɪɴ ᴊᴀᴜʜ sᴇᴍᴀᴋɪɴ ᴛᴀʜᴜ.",
"🧠 Kᴇᴄᴇʀᴅᴀsᴀɴ ʙᴜᴛᴜʜ ᴛɪɴᴅᴀᴋᴀɴ.",
"💪 Tᴀɴɢɢᴜʜ ɪᴛᴜ ᴋᴇʜᴀʀᴜsᴀɴ.",
"🌙 Sᴇᴘɪ ʙᴜᴋᴀɴ ʟᴇᴍᴀʜ.",
"🔥 Sᴇʟᴀʟᴜ ᴀᴅᴀ ᴊᴀʟᴀɴ.",
"🌍 Kᴀᴍᴜ ᴀᴅᴀʟᴀʜ ᴘɪʟɪʜᴀɴ.",
"🚀 Sᴇᴛɪᴀᴘ ʜᴀʀɪ ʙᴀʀᴜ.",
"💥 Jᴀɴɢᴀɴ ɴʏᴇʀᴀʜ.",
"🌟 Kᴀᴍᴜ ᴀᴅᴀʟᴀʜ ᴀʟᴀsᴀɴ.",
"🔥 Jᴀᴅɪʟᴀʜ ᴘᴇɴᴇʀᴀɴɢ.",
"🌈 Kᴇʙᴀʜᴀɢɪᴀᴀɴ ᴅɪ ᴅɪʀɪ.",
"🧭 Jᴀʟᴀɴɪ ᴘʀᴏsᴇs.",
"💪 Kᴇʙᴇʀʜᴀsɪʟᴀɴ ᴅɪᴍᴜʟᴀɪ ᴋᴇɴᴇᴋᴀᴛᴀɴ.",
"🌍 Tɪᴅᴀᴋ ᴀᴅᴀ ʙᴀᴛᴀs ʜɪᴅᴜᴘ.",
"🔥 Jᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ᴍᴇɴᴄᴏʙᴀ.",
"🌟 Kᴇʙᴇʀᴀɴɪᴀɴ ᴍᴇɴᴇɴᴛᴜᴋᴀɴ ᴍᴀsᴀ ᴅᴇᴘᴀɴ.",
"💥 Sᴇʟᴀʟᴜ ᴀᴅᴀ ᴘᴇʟᴜᴀɴɢ.",
"🌈 Hɪᴅᴜᴘ ʙᴜᴋᴀɴ ᴍᴇɴɢᴇʟᴜʜ.",
"🚀 Sᴇᴍᴀᴋɪɴ ᴊᴀᴜʜ ᴍᴀᴋɴᴀ ʜɪᴅᴜᴘ.",
"🧠 Pɪᴋɪʀᴀɴ ᴍᴇɴᴇɴᴛᴜᴋᴀɴ ʜɪᴅᴜᴘ.",
"💪 Tɪᴅᴀᴋ ᴀᴅᴀ ʜᴀsɪʟ ᴛᴀɴᴘᴀ ᴜsᴀʜᴀ.",
"🌍 Hɪᴅᴜᴘ ʙᴇʀᴜʙᴀʜ ᴛᴇʀᴜs.",
"🔥 Tᴇᴛᴀᴘ ʙᴇʀᴊᴀʟᴀɴ.",
"🌟 Jᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ʙᴇʀᴜsᴀʜᴀ.",
"💥 Kᴀᴍᴜ ᴀᴅᴀʟᴀʜ ᴘᴇʀᴜʙᴀʜᴀɴ.",
"🌈 Kᴇʜɪᴅᴜᴘᴀɴ ɪɴᴅᴀʜ ᴊɪᴋᴀ ᴅɪᴊᴀʟᴀɴɪ.",
"🚀 Jᴀᴅɪʟᴀʜ ᴋᴜᴀᴛ ʜᴀʀɪ ɪɴɪ.",
"🧭 Tᴇᴛᴀᴘ ᴊᴀʟᴀɴ ᴍᴇsᴋɪ ʙᴇʀᴀᴛ.",
"💪 Kᴀᴍᴜ ʟᴇʙɪʜ ᴋᴜᴀᴛ ᴅᴀʀɪ ɢᴀɢᴀʟ.",
"🌍 Hɪᴅᴜᴘ ᴀᴅᴀʟᴀʜ ᴘᴇʀᴊᴜᴀɴɢᴀɴ.",
"🔥 Jᴀɴɢᴀɴ ᴍᴇɴʏᴇʀᴀʜ.",
"🌟 ᴊᴀɴɢᴀɴ ᴛᴜɴᴅᴀ sᴜᴋsᴇs.",
"💥 ᴋᴀᴍᴜ ʙɪsᴀ ʟᴇʙɪʜ ʙᴀɪᴋ.",
"🌈 ᴘʀᴏsᴇs ʟᴇʙɪʜ ᴘᴇɴᴛɪɴɢ.",
"🚀 ᴊᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ʙᴇʀʟᴀᴛɪʜ.",
"🧠 ᴘᴇʀᴜʙᴀʜᴀɴ ᴅᴀʀɪ ᴅɪʀɪ.",
"💪 ᴋᴇʜɪᴅᴜᴘᴀɴ ᴍᴇɴᴜɴᴛᴜᴛ ᴋᴇʙᴇʀᴀɴɪᴀɴ.",
"🌙 ʟᴀɴɢᴋᴀʜ ᴋᴇᴄɪʟ ʟᴇʙɪʜ ʙᴀɪᴋ.",
"🔥 ᴊᴀᴅɪʟᴀʜ ʟᴇʙɪʜ ᴋᴜᴀᴛ.",
"🌍 ᴅᴜɴɪᴀ ʙᴇʀᴜʙᴀʜ.",
"🚀 ᴊᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ʙᴇʀᴍɪᴍᴘɪ.",
"💥 sᴇᴛɪᴀᴘ ʜᴀʀɪ ᴘᴇʟᴜᴀɴɢ ʙᴀʀᴜ.",
"🌈 ᴋᴇʙᴀʜᴀɢɪᴀᴀɴ ᴅᴀʀɪ ᴅɪʀɪ.",
"🧭 ᴛᴇᴛᴀᴘ ᴊᴀʟᴀɴ.",
"💪 ᴋᴇʙᴇʀʜᴀsɪʟᴀɴ ᴅᴀʀɪ ᴋᴇɴᴇᴋᴀᴛᴀɴ.",
"🌍 ᴋᴀᴍᴜ ʙɪsᴀ ᴍᴇɴᴜʙᴀʜ.",
"🔥 ᴊᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ᴍᴇɴᴄᴏʙᴀ.",
"🌟 ᴍᴀsᴀ ᴅᴇᴘᴀɴ ʜᴀʀɪ ɪɴɪ.",
"💥 ᴊᴀɴɢᴀɴ ɴʏᴇʀᴀʜ.",
"🌈 ʜɪᴅᴜᴘ ɪᴛᴜ ᴘᴇʀᴊᴜᴀɴɢᴀɴ.",
"🚀 ᴋᴀᴍᴜ ʟᴇʙɪʜ ᴋᴜᴀᴛ.",
"🧠 ᴘɪᴋɪʀᴀɴ ᴍᴇɴᴇɴᴛᴜᴋᴀɴ ʜɪᴅᴜᴘ.",
"💪 ᴛɪᴅᴀᴋ ᴀᴅᴀ ʜᴀsɪʟ ᴛᴀɴᴘᴀ ᴜsᴀʜᴀ.",
"🌍 ʜɪᴅᴜᴘ ʙᴇʀᴜʙᴀʜ.",
"🔥 ᴛᴇᴛᴀᴘ ᴍᴇʟᴀɴɢᴋᴀʜ.",
"🌟 ᴊᴀɴɢᴀɴ ʙᴇʀʜᴇɴᴛɪ ᴍᴇɴᴄᴏʙᴀ.",
"💥 ᴋᴀᴍᴜ ᴀᴅᴀʟᴀʜ ᴘᴇʀᴜʙᴀʜᴀɴ.",
"🌈 ʜɪᴅᴜᴘ ɪɴᴅᴀʜ ᴊɪᴋᴀ ᴅɪᴊᴀʟᴀɴɪ.",
"🚀 ᴊᴀᴅɪʟᴀʜ ᴋᴜᴀᴛ.",
# ================= GALAU / KANGEN / KODE KERAS =================
"🌧 Aku baik-baik saja, hanya saja tidak sekuat dulu.",
"💔 Rasa ini tidak pergi, cuma terbiasa diam.",
"🌙 Malam selalu tahu siapa yang sedang kehilangan.",
"🕊 Aku rindu, tapi tidak punya alasan untuk kembali.",
"🚬 Kadang yang paling sakit adalah pura-pura biasa saja.",
"📵 Aku tidak hilang, hanya tidak lagi dicari.",
"🖤 Luka tidak selalu terlihat, tapi selalu terasa.",
"⏳ Waktu tidak menyembuhkan, hanya membiasakan.",
"🌧 Hujan paling jujur adalah yang turun tanpa suara.",
"💬 Aku diam bukan berarti lupa.",

"🧠 Kode keras: jangan berharap dari yang sudah pergi.",
"⚠️ Tidak semua yang datang akan tinggal.",
"🔐 Jangan buka hati untuk orang yang pernah menutupmu.",
"📌 Yang peduli tidak akan membuatmu menunggu.",
"🧊 Hati yang terlalu sering dingin, akan lupa cara hangat.",
"🚫 Jangan kejar yang tidak ingin dikejar.",
"🧷 Yang tulus tidak perlu dipaksa bertahan.",
"📉 Ekspektasi tinggi = luka lebih dalam.",
"🧨 Jangan letakkan kebahagiaan di tangan orang lain.",
"🧭 Kalau dia mau, dia akan tetap tinggal.",
"🕳 Jangan jatuh di lubang yang sama dua kali.",

"💔 Aku belajar bahwa kehilangan itu juga bentuk pelajaran.",
"🌫 Kadang yang pergi bukan karena benci, tapi karena lelah.",
"🖤 Aku kangen, tapi aku juga harus waras.",
"🌧 Hujan ini mirip perasaan, datang tanpa izin lalu pergi diam-diam.",
"📍 Tidak semua cerita harus punya akhir bahagia.",
"🧠 Yang mengerti tidak akan membuatmu menjelaskan berkali-kali.",
"⛓ Jangan mengikat yang memang ingin bebas.",
"🪞 Yang pergi akan tetap jadi bayangan di ingatan.",
"🧩 Tidak semua yang hilang harus dicari lagi.",
"🌙 Aku sudah terbiasa sendiri, bahkan saat ramai."
]

def get_quote():
    return random.choice(QUOTES)
